import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f4eb', overflow: 'hidden' },
  swipeUnderlay: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  swipeLayer: { flex: 1 },
  mainContent: { paddingHorizontal: 20, paddingTop: 84, paddingBottom: 120 },
  title: { fontSize: 40, fontWeight: '800', letterSpacing: -1, color: '#3c2f2f', textAlign: 'center' },
  subtitle: { fontSize: 16, lineHeight: 22, color: '#666', textAlign: 'center', marginBottom: 24 },
  stats: { fontSize: 16, color: '#3c2f2f', fontWeight: '700', textAlign: 'center', marginBottom: 32 },
  heroCard: { borderRadius: 28, paddingHorizontal: 24, paddingTop: 66, paddingBottom: 28, marginBottom: 24, overflow: 'hidden', position: 'relative' },
  heroCornerButton: { position: 'absolute', top: 16, width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', zIndex: 2 },
  heroCornerLeft: { left: 16 },
  heroCornerRight: { right: 16 },
  heroCornerText: { fontSize: 18, fontWeight: '900', lineHeight: 20 },
  brandMark: { width: 188, height: 188, borderRadius: 28, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginBottom: 18, overflow: 'hidden' },
  brandImage: { width: '100%', height: '100%' },
  brandMarkText: { fontSize: 22, fontWeight: '800', letterSpacing: 1 },
  heroEyebrow: { fontSize: 12, fontWeight: '800', letterSpacing: 1.6, textTransform: 'uppercase', marginBottom: 12 },
  homeStatRow: { flexDirection: 'row', justifyContent: 'center', gap: 10 },
  heroStatPill: { alignSelf: 'center', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999, marginBottom: 18 },
  heroStatText: { fontSize: 13, fontWeight: '800', letterSpacing: 0.4 },
  homeButtons: { width: '100%', alignItems: 'center' },
  homePrimaryActions: { width: '100%', marginBottom: 18 },
  homePrimaryButton: { paddingVertical: 20, paddingHorizontal: 22, borderRadius: 24, marginBottom: 12, width: '100%' },
  homePrimaryTitle: { fontSize: 22, fontWeight: '900', marginBottom: 6 },
  homePrimaryMeta: { fontSize: 14, lineHeight: 20, opacity: 0.88 },
  homeUtilityGrid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 8 },
  homeUtilityTile: { width: '48%', minHeight: 106, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 14, justifyContent: 'space-between' },
  homeUtilityTitle: { fontSize: 15, fontWeight: '900', marginBottom: 8 },
  homeUtilityMeta: { fontSize: 12, lineHeight: 16 },
  bigButton: { paddingVertical: 22, paddingHorizontal: 60, borderRadius: 22, marginBottom: 14, width: '100%', alignItems: 'center' },
  secondaryButton: { paddingVertical: 18, paddingHorizontal: 28, borderRadius: 18, marginBottom: 12, width: '100%', alignItems: 'center' },
  buttonText: { color: '#f8f4eb', fontSize: 19, fontWeight: '700', letterSpacing: 0.2 },
  secondaryButtonText: { color: '#3c2f2f', fontSize: 17, fontWeight: '700' },
  fullScreenView: { flex: 1, width: '100%', padding: 20 },
  thinkingScreen: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center', padding: 16 },
  thinkingCard: { width: '100%', borderRadius: 24, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 18, alignItems: 'stretch' },
  thinkingTitle: { fontSize: 24, fontWeight: '900', marginBottom: 8, letterSpacing: -0.3 },
  thinkingBody: { fontSize: 14, lineHeight: 20, textAlign: 'center' },
  thinkingStepList: { marginTop: 12, gap: 8 },
  thinkingStepCard: { borderRadius: 16, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10 },
  thinkingStepTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 3 },
  thinkingStepLabel: { fontSize: 13, fontWeight: '900' },
  thinkingStepBadge: { minWidth: 42, borderRadius: 999, borderWidth: 1, paddingVertical: 3, paddingHorizontal: 8, alignItems: 'center' },
  thinkingStepBadgeText: { fontSize: 10, fontWeight: '900', letterSpacing: 0.5, textTransform: 'uppercase' },
  thinkingStepValue: { fontSize: 12, lineHeight: 17 },
  thinkingPreviewPanel: { marginTop: 12, borderRadius: 18, borderWidth: 1, padding: 12 },
  thinkingPreviewEyebrow: { fontSize: 11, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.1, marginBottom: 10 },
  thinkingPreviewCard: { borderRadius: 16, borderWidth: 1, padding: 12 },
  thinkingPreviewTitle: { fontSize: 18, fontWeight: '900', lineHeight: 22, marginBottom: 6 },
  thinkingPreviewBody: { fontSize: 12, lineHeight: 17 },
  thinkingPreviewMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  thinkingPreviewMetaItem: { width: '47%', borderRadius: 12, borderWidth: 1, padding: 8, minHeight: 64 },
  thinkingPreviewMetaLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 6 },
  thinkingPreviewMetaValue: { fontSize: 13, fontWeight: '800', lineHeight: 16 },
  thinkingCorrectionList: { marginTop: 10, gap: 4 },
  thinkingCorrectionLine: { fontSize: 11, lineHeight: 15 },
  thinkingFilingRail: { borderRadius: 16, borderWidth: 1, padding: 10, gap: 8 },
  thinkingFilingStop: { borderRadius: 14, borderWidth: 1, padding: 10 },
  thinkingFilingConnector: { height: 2, marginHorizontal: 12, opacity: 0.8 },
  formTitle: { fontSize: 28, fontWeight: '800', color: '#3c2f2f', marginBottom: 18, textAlign: 'center', letterSpacing: -0.5 },
  contextText: { fontSize: 16, color: '#555', textAlign: 'center', marginBottom: 18 },
  categoryButton: { backgroundColor: '#e6d9c2', paddingVertical: 16, paddingHorizontal: 18, borderRadius: 16, width: '100%', alignItems: 'center', marginBottom: 12 },
  categoryButtonText: { color: '#3c2f2f', fontSize: 16, fontWeight: '700' },
  searchInput: { backgroundColor: 'white', borderWidth: 1, borderColor: '#ccc', borderRadius: 16, padding: 14, fontSize: 17, width: '100%', marginBottom: 20 },
  cardSortRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  cardSortButton: { flex: 1, borderRadius: 999, borderWidth: 1, paddingVertical: 11, paddingHorizontal: 12, alignItems: 'center' },
  cardSortButtonText: { fontSize: 13, fontWeight: '900' },
  masterBoxScroll: { width: '100%' },
  masterBoxScrollContent: { paddingBottom: 36 },
  masterBoxGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, justifyContent: 'center', paddingBottom: 18 },
  masterBox: { width: '47%', minHeight: 178, borderRadius: 22, borderWidth: 1, padding: 14, alignItems: 'center', shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 5 },
  masterBoxIcon: { width: 92, height: 62, borderRadius: 10, paddingTop: 10, paddingHorizontal: 10, marginBottom: 12, overflow: 'hidden' },
  masterBoxCardBack: { height: 30, borderRadius: 5, marginHorizontal: 8, marginBottom: -18, opacity: 0.78 },
  masterBoxCardFront: { height: 40, borderRadius: 5, borderTopWidth: 7, borderTopColor: '#d0a05f' },
  masterBoxRange: { fontSize: 16, fontWeight: '900', textAlign: 'center', marginBottom: 5 },
  masterBoxTitle: { fontSize: 12, fontWeight: '700', textAlign: 'center', lineHeight: 16, minHeight: 32 },
  masterBoxCount: { marginTop: 10, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, fontSize: 11, fontWeight: '900', overflow: 'hidden' },
  drawerScene: { flex: 1, minHeight: 560, borderRadius: 20, overflow: 'hidden', marginBottom: 18, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 18 },
  drawerTopRail: { height: 18, borderRadius: 5, marginHorizontal: 38, marginBottom: 16, opacity: 0.72 },
  drawerInnerWell: { flex: 1, borderRadius: 14, paddingHorizontal: 4, paddingTop: 24, overflow: 'hidden' },
  drawerCardsContent: { paddingTop: 8, paddingBottom: 120, paddingHorizontal: 12, alignItems: 'stretch' },
  drawerFrontRail: { height: 24, borderRadius: 5, marginHorizontal: 18, marginTop: 12, opacity: 0.9 },
  cardFileBox: { borderRadius: 8, borderWidth: 1, paddingHorizontal: 12, paddingTop: 14, paddingBottom: 18, marginBottom: 16 },
  cardFileLid: { height: 56, borderTopLeftRadius: 8, borderTopRightRadius: 8, borderWidth: 1, borderBottomWidth: 0, marginHorizontal: 14, marginBottom: -8 },
  cardFileRail: { height: 16, borderRadius: 3, marginHorizontal: 34, marginBottom: 10 },
  cardStackHeader: { borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, borderWidth: 1, marginBottom: 12 },
  cardStackHeaderTitle: { fontSize: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.4, textAlign: 'center', marginBottom: 4 },
  cardStackHeaderBody: { fontSize: 14, lineHeight: 20, textAlign: 'center' },
  cardStackContent: { paddingTop: 64, paddingBottom: 120, alignItems: 'center' },
  categoryList: { flex: 1 },
  categoryRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  categoryItem: { padding: 18, backgroundColor: 'white', borderRadius: 18, borderLeftWidth: 5 },
  categoryText: { fontSize: 16, color: '#3c2f2f', fontWeight: '700', lineHeight: 22 },
  emptyRangeText: { color: '#666', fontSize: 14, marginBottom: 12, fontStyle: 'italic' },
  addButton: { backgroundColor: '#3c2f2f', width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 6 },
  addButtonText: { color: '#f8f4eb', fontSize: 22, fontWeight: 'bold' },
  chevronButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  chevron: { fontSize: 18, color: '#3c2f2f' },
  cardStackWrap: { width: '100%', alignSelf: 'stretch', marginBottom: 18 },
  cardStackShadow: { borderRadius: 8 },
  cardStackBackplate: { position: 'absolute', left: 0, right: 0, top: 10, bottom: -4, borderRadius: 7, borderWidth: 1, opacity: 0.38 },
  cardListItem: { width: '100%', alignSelf: 'stretch', backgroundColor: 'white', padding: 22, paddingTop: 18, borderRadius: 7, borderTopWidth: 1, borderLeftWidth: 0, borderWidth: 1, borderColor: '#3c2f2f', minHeight: 306 },
  cardRule: { height: 1, marginTop: 14, marginBottom: 16, opacity: 0.55 },
  noteLines: { position: 'absolute', left: 22, right: 22, top: 144, gap: 29, opacity: 0.32 },
  noteLine: { height: 1 },
  cardWearTop: { position: 'absolute', left: 0, right: 0, top: 0, height: 18, opacity: 0.18 },
  cardWearCornerLeft: { position: 'absolute', left: 6, bottom: 6, width: 36, height: 36, borderLeftWidth: 1, borderBottomWidth: 1, opacity: 0.5 },
  cardWearCornerRight: { position: 'absolute', right: 6, top: 6, width: 36, height: 36, borderRightWidth: 1, borderTopWidth: 1, opacity: 0.5 },
  cardCornerPin: { position: 'absolute', width: 6, height: 6, borderRadius: 3, top: 14, left: 16, opacity: 0.42 },
  cardMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10, marginBottom: 6 },
  cardMetaLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  cardMetaRight: { alignItems: 'flex-end' },
  cardAddress: { fontSize: 22, color: '#666', fontWeight: '700', fontStyle: 'italic', letterSpacing: 0.6 },
  cardDate: { fontSize: 12, fontWeight: '700', fontStyle: 'italic' },
  cardCategory: { fontSize: 13, fontWeight: '700' },
  cardTitle: { fontSize: 20, fontWeight: '800', color: '#3c2f2f', marginVertical: 8 },
  cardPreview: { fontSize: 15, color: '#555', lineHeight: 23, minHeight: 76 },
  drawerCardCategory: { fontSize: 14, fontWeight: '700', marginTop: 4 },
  drawerCardHint: { position: 'absolute', left: 22, bottom: 20, fontSize: 12, fontWeight: '700' },
  drawerCardFooter: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  drawerCardFooterText: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, fontSize: 11, fontWeight: '800', maxWidth: '46%' },
  cardFooterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  chip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1 },
  chipText: { fontSize: 12, fontWeight: '700' },
  statusChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  statusChipText: { fontSize: 12, fontWeight: '800', letterSpacing: 0.3 },
  cardViewerScroll: { flex: 1 },
  cardViewer: { padding: 20, paddingTop: 70, paddingBottom: 40 },
  cardViewerShell: { borderRadius: 30, padding: 24, borderWidth: 1, borderTopWidth: 16, overflow: 'hidden' },
  cardViewerBrandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 18 },
  cardViewerLogo: { width: 34, height: 34, borderRadius: 10 },
  cardViewerBrandText: { fontSize: 12, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' },
  cardViewerWatermark: { position: 'absolute', width: 170, height: 170, right: -34, bottom: -36, opacity: 0.055 },
  cardViewerRule: { height: 1, marginVertical: 18 },
  cardViewerHeader: { marginBottom: 18 },
  cardViewerMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14, gap: 12 },
  cardViewerMetaGroup: { flex: 1, gap: 8 },
  cardViewerAddress: { fontSize: 18, color: '#666', textAlign: 'center' },
  cardViewerTitle: { fontSize: 28, fontWeight: '800', color: '#3c2f2f', textAlign: 'center', marginVertical: 12, letterSpacing: -0.4 },
  cardViewerContent: { fontSize: 17, lineHeight: 26, color: '#333', marginTop: 20 },
  cardViewerSection: { marginTop: 22 },
  threadIntroText: { fontSize: 14, lineHeight: 20, textAlign: 'center' },
  threadGraphCard: { borderRadius: 22, borderWidth: 1, padding: 14 },
  threadGraphCanvas: { borderRadius: 22, borderWidth: 1, alignSelf: 'center', position: 'relative', overflow: 'hidden' },
  threadRing: { position: 'absolute', borderRadius: 999, borderWidth: 1, opacity: 0.4 },
  threadNode: { position: 'absolute', borderRadius: 20, borderWidth: 1.5, paddingHorizontal: 8, paddingVertical: 10, alignItems: 'center', justifyContent: 'center' },
  threadNodeCenter: { borderWidth: 2.5, shadowOpacity: 0.12, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  threadNodeSecondary: { borderStyle: 'dashed' },
  threadNodeAddress: { fontSize: 10, fontWeight: '900', letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 5 },
  threadNodeTitle: { fontSize: 12, fontWeight: '800', lineHeight: 15, textAlign: 'center' },
  threadLegendRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14, justifyContent: 'center' },
  threadLegendChip: { borderRadius: 999, borderWidth: 1, paddingVertical: 7, paddingHorizontal: 12 },
  threadLegendLabel: { fontSize: 11, fontWeight: '800', textAlign: 'center' },
  threadOverflowNote: { fontSize: 12, lineHeight: 17, textAlign: 'center', marginTop: 10 },
  sectionTitle: { fontSize: 13, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 10 },
  relatedCardButton: { paddingVertical: 12, paddingHorizontal: 14, borderRadius: 14, borderWidth: 1, marginBottom: 10 },
  relatedCardTitle: { fontSize: 15, fontWeight: '700', marginBottom: 4 },
  relatedCardMeta: { fontSize: 13, fontWeight: '600' },
  suggestionPanel: { borderRadius: 16, borderWidth: 1, marginTop: -4, marginBottom: 12, overflow: 'hidden' },
  suggestionItem: { paddingVertical: 12, paddingHorizontal: 14, borderBottomWidth: 1 },
  suggestionTitle: { fontSize: 15, fontWeight: '800', marginBottom: 3 },
  suggestionMeta: { fontSize: 13, fontWeight: '600' },
  sourceViewerPanel: { borderRadius: 18, borderWidth: 1, padding: 16 },
  sourceViewerType: { fontSize: 12, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 },
  sourceViewerTitle: { fontSize: 18, fontWeight: '800', lineHeight: 24, marginBottom: 6 },
  sourceViewerDetail: { fontSize: 14, fontWeight: '700', lineHeight: 20, marginBottom: 4 },
  sourceViewerNote: { fontSize: 15, lineHeight: 22, marginTop: 10 },
  sourceUrlButton: { borderWidth: 1, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, marginTop: 10 },
  sourceUrlText: { fontSize: 14, fontWeight: '800' },
  cardForm: { width: '100%', padding: 20 },
  label: { fontSize: 15, color: '#555', marginTop: 15, marginBottom: 8, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
  input: { backgroundColor: 'white', borderWidth: 1, borderColor: '#ccc', borderRadius: 16, padding: 14, fontSize: 17, width: '100%', marginBottom: 12 },
  contentInput: { height: 180, textAlignVertical: 'top' },
  quickCaptureInput: { minHeight: 240, textAlignVertical: 'top' },
  askCardsInput: { minHeight: 120, textAlignVertical: 'top' },
  askAnswerPanel: { borderRadius: 24, borderWidth: 1, padding: 18, marginTop: 18 },
  askAnswerEyebrow: { fontSize: 12, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 10 },
  askAnswerText: { fontSize: 17, lineHeight: 27 },
  askSection: { marginTop: 18 },
  followUpButton: { borderRadius: 14, borderWidth: 1, paddingVertical: 11, paddingHorizontal: 13, marginBottom: 9 },
  followUpText: { fontSize: 14, fontWeight: '800', lineHeight: 20 },
  inboxCard: { borderRadius: 22, borderWidth: 1, padding: 18, marginBottom: 14 },
  inboxMeta: { fontSize: 12, fontWeight: '800', letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 8 },
  inboxTitle: { fontSize: 20, fontWeight: '900', lineHeight: 26, marginBottom: 8 },
  inboxPreview: { fontSize: 15, lineHeight: 23, marginBottom: 10 },
  inboxSource: { fontSize: 13, fontWeight: '700', lineHeight: 19, marginBottom: 12 },
  inboxActionRow: { flexDirection: 'row', gap: 8, marginTop: 4 },
  inboxActionButton: { flex: 1, borderRadius: 14, paddingVertical: 12, paddingHorizontal: 12, alignItems: 'center' },
  inboxActionButtonText: { fontSize: 12, fontWeight: '900', textAlign: 'center' },
  todoCardRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  todoCheckButton: { width: 28, height: 28, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  todoCheckMark: { fontSize: 16, fontWeight: '900', lineHeight: 18 },
  todoRowBody: { flex: 1 },
  todoEditPanel: { borderRadius: 22, borderWidth: 1, padding: 16, marginBottom: 16 },
  todoDragHandle: { width: 28, height: 28, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  todoDragHandleText: { fontSize: 16, fontWeight: '900', lineHeight: 18 },
  todoMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  todoMetaPill: { borderRadius: 999, borderWidth: 1, paddingVertical: 4, paddingHorizontal: 10 },
  todoMetaPillText: { fontSize: 12, fontWeight: '800' },
  todoLinkedCardButton: { borderRadius: 999, borderWidth: 1, paddingVertical: 4, paddingHorizontal: 10, marginRight: 8, marginBottom: 8 },
  todoLinkedCardText: { fontSize: 12, fontWeight: '800' },
  aiAssistPanel: { borderRadius: 22, borderWidth: 1, padding: 16, marginTop: 6, marginBottom: 6 },
  aiAssistHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  aiAssistTitle: { fontSize: 18, fontWeight: '900', marginBottom: 5 },
  aiAssistBody: { fontSize: 14, lineHeight: 20 },
  aiAssistButton: { paddingVertical: 12, paddingHorizontal: 14, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  aiAssistButtonText: { fontSize: 13, fontWeight: '900' },
  aiThinkingCard: { borderRadius: 16, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10, marginTop: 12 },
  aiThinkingTitle: { fontSize: 14, fontWeight: '900', marginBottom: 4 },
  aiThinkingBody: { fontSize: 12, lineHeight: 17 },
  aiThinkingStepList: { marginTop: 10, gap: 6 },
  aiThinkingStepRow: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 8 },
  aiThinkingStepLabel: { fontSize: 12, fontWeight: '900', marginBottom: 1 },
  aiThinkingStepValue: { fontSize: 11, lineHeight: 15 },
  aiThinkingStepBadge: { minWidth: 40, borderRadius: 999, borderWidth: 1, paddingVertical: 3, paddingHorizontal: 8, alignItems: 'center' },
  aiThinkingStepBadgeText: { fontSize: 10, fontWeight: '900', letterSpacing: 0.4, textTransform: 'uppercase' },
  aiThinkingPathRow: { flexDirection: 'row', gap: 6, marginTop: 10 },
  aiThinkingPathStop: { flex: 1, borderRadius: 12, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 7 },
  aiThinkingPathLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.7, marginBottom: 4 },
  aiThinkingPathValue: { fontSize: 12, fontWeight: '800' },
  aiProgressCard: { borderRadius: 18, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 12, marginTop: 14 },
  aiProgressTitle: { fontSize: 14, fontWeight: '900', marginBottom: 6 },
  aiProgressLine: { fontSize: 13, lineHeight: 19, marginTop: 2 },
  aiSuggestionCard: { borderRadius: 18, borderWidth: 1, padding: 14, marginTop: 14 },
  aiSuggestionEyebrow: { fontSize: 11, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 7 },
  aiSuggestionMetaRow: { flexDirection: 'row', marginBottom: 8 },
  aiSuggestionStatusBadge: { borderRadius: 999, borderWidth: 1, paddingVertical: 5, paddingHorizontal: 10 },
  aiSuggestionStatusText: { fontSize: 11, fontWeight: '900', letterSpacing: 0.6, textTransform: 'uppercase' },
  aiSuggestionTitle: { fontSize: 18, fontWeight: '900', lineHeight: 24, marginBottom: 8 },
  aiSuggestionLine: { fontSize: 13, fontWeight: '700', lineHeight: 19, marginBottom: 4 },
  aiSuggestionReason: { fontSize: 14, lineHeight: 21, marginTop: 8 },
  aiAlternativeBlock: { marginTop: 10 },
  aiAlternativeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  aiAlternativeChip: { borderRadius: 14, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 8, maxWidth: '100%' },
  aiAlternativeChipText: { fontSize: 12, fontWeight: '800', lineHeight: 16 },
  aiActionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  aiActionButton: { borderRadius: 999, paddingVertical: 9, paddingHorizontal: 12 },
  aiActionButtonText: { fontSize: 12, fontWeight: '900' },
  sourcePanel: { borderRadius: 22, borderWidth: 1, padding: 16, marginTop: 10, marginBottom: 4 },
  sourcePanelTitle: { fontSize: 18, fontWeight: '900', marginBottom: 5 },
  sourcePanelHelp: { fontSize: 14, lineHeight: 20, marginBottom: 2 },
  sourceNoteInput: { minHeight: 96, textAlignVertical: 'top' },
  segmentedRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 4 },
  segmentedButton: { paddingVertical: 12, paddingHorizontal: 16, borderRadius: 999, borderWidth: 1 },
  segmentedButtonText: { fontSize: 14, fontWeight: '700' },
  saveButton: { backgroundColor: '#2c2525', padding: 18, borderRadius: 16, marginTop: 25, alignItems: 'center' },
  saveButtonText: { color: 'white', fontSize: 18, fontWeight: '700' },
  deleteButton: { backgroundColor: '#8b3a2f', padding: 18, borderRadius: 16, marginTop: 12, alignItems: 'center' },
  deleteButtonText: { color: 'white', fontSize: 18, fontWeight: '700' },
  cancelButton: { padding: 16, alignItems: 'center', marginTop: 30 },
  cancelButtonText: { color: '#777', fontSize: 16, fontWeight: '600' },
  emptyText: { textAlign: 'center', color: '#666', fontSize: 17, marginTop: 100 },
  helperText: { textAlign: 'center', color: '#666', fontSize: 14, marginBottom: 16, lineHeight: 20 },
  settingsPanel: { borderRadius: 22, borderWidth: 1, padding: 16, marginBottom: 14, width: '100%' },
  settingsPanelTitle: { fontSize: 18, fontWeight: '900', marginBottom: 8, textAlign: 'center' },
  brandFooter: { textAlign: 'center', fontSize: 13, fontWeight: '700', letterSpacing: 0.6, marginTop: 10 },
  helpCard: { borderRadius: 22, padding: 18, borderWidth: 1, marginBottom: 14 },
  helpTitle: { fontSize: 18, fontWeight: '800', marginBottom: 8 },
  helpBody: { fontSize: 15, lineHeight: 22 },
  helpBadge: { alignSelf: 'center', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, marginBottom: 16 },
  helpBadgeText: { fontSize: 12, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase' },
});
